language: python
python: '2.7'
services:
- rabbitmq
before_install:
- sudo apt-get install python-software-properties
- sudo add-apt-repository -y cloud-archive:icehouse
- sudo apt-get update -qq
install:
- sudo pip install ansible
- '{ echo ''[defaults]''; echo ''roles_path = ../''; } >> ansible.cfg'
script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- |
  ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
- |
  ansible-playbook -i tests/inventory tests/test.yml -t neutron-dhcp-agent --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
- service neutron-dhcp-agent status
notifications:
  slack:
    secure: aeA4rBVFyLis8WQywrkBe9Z/k0dQ4aMrrMvlksDriy/SZl6bdvivrdvxVNIS2u/59VZwpR0OD8F5rwy3/UnvSL4n9lM0ukp6zJoJvuOaoh7ivjqX+PAELENSmEQMaxZh4v6Cm48EmgWngfgZP3gQ4agwDWlewUM8o0vyQG7rCXA/xVE34OyzI8Vcz9639tpZk/s43RCiDRQ9lEfu+yjP/16FcXbTOGi2cFbya475NmOB6NGy4eIYMVXsQxNsVbkKtpWFQcb8w4QUOwhKUpdRH7pBRMeaFdZExRJ9pnEta0tHvP6972azLCcwnu9YcUp4wLlpM80FqvaFPNV6fxGiyGPWBhiOIPQo52ne5SUmjS6k9Gb8x0ipDBxl6uJL4NeibwZ6xHBuQZaHVZ4sRz4mtXY2NijKofOPKBrub9znOXt8TNsemRwNEIFSbLxAc9O4TNcccVSJSnHPREvU48ZBgL9gc6GcT+Z+XRe93Mj7MkRgoFzINI1KcIqXz92cBX/GOBww0cmaK94hA/WfgfGVf+WQ5H2ResjcEuDFrBS3RBReCGbDx6HG2fjn0IL+nP2TXqxUW4Lc3FfW5OFlfkUO4lLdjgxgwcY0O1dgLs3Q1PX/3KzrP6svRuwVaek2teDUmBwI9juYDBOC9Nu/0SckTl3m5uaKtSgUlQUGNwFISYI=
